# Generated by Django 4.2.1 on 2023-09-08 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_tag_opinion_date_remove_opinion_tags_opinion_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 11, 27, 37, 765508, tzinfo=datetime.timezone.utc)),
        ),
    ]
