# Generated by Django 4.2.1 on 2023-09-08 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_opinion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 13, 19, 0, 590720, tzinfo=datetime.timezone.utc)),
        ),
    ]
