# Generated by Django 4.2.1 on 2023-09-09 11:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_opinion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 11, 44, 18, 138952, tzinfo=datetime.timezone.utc)),
        ),
    ]
