# Generated by Django 4.2.1 on 2023-09-09 11:45

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_opinion_likes_user_following_alter_opinion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 11, 45, 11, 202826, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_opinions', to=settings.AUTH_USER_MODEL),
        ),
    ]
