# Generated by Django 4.2.1 on 2023-09-09 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_opinion_date_alter_opinion_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 13, 20, 36, 36772, tzinfo=datetime.timezone.utc)),
        ),
    ]
