# Generated by Django 4.2.1 on 2023-09-17 13:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_opinion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='tags',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 13, 0, 2, 595247, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_opinions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
