# Generated by Django 4.2.1 on 2023-09-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_opinion_tags_alter_opinion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
